version: "2"

services:
  main:
    build: .
    ports:
     - "80:80"
    restart: unless-stopped
    command: bundle exec rackup -o 0.0.0.0 -p 80
    networks:
      - default
      - nginx-proxy

  crawl_mention:
    build: .
    restart: unless-stopped
    command: bundle exec ruby crawl_mention.rb
    networks:
      - default

  mongodb:
    image: mongo:3.4.24
    command: mongod
    restart: unless-stopped
    volumes:
      - mongodb:/data/db
    networks:
      - default

volumes:
  mongodb:

networks:
  nginx-proxy:
    external: true
