version: "2"

services:
  main:
    build: .
    ports:
     - "80:80"
    restart: unless-stopped
    command: bundle exec rackup -o 0.0.0.0 -p 80
    networks:
      - default
      - nginx-proxy

  crawl_mention:
    build: .
    restart: unless-stopped
    command: bundle exec ruby crawl_mention.rb
    networks:
      - default

  process_task:
    build: .
    restart: on-failure
    command: bundle exec ruby process_task.rb
    environment:
      WORKER_URL: "http://diyscan-worker_main_1:5000"
      WEB_BASE_URL: "https://diyscan.airytail.co"
    networks:
      - default
      - diyscan

  mongodb:
    image: mongo:3.4.24
    command: mongod
    restart: unless-stopped
    volumes:
      - mongodb:/data/db
    networks:
      - default

volumes:
  mongodb:

networks:
  diyscan:
    external: true
  nginx-proxy:
    external: true
